version: '2.2'

services:
  web:
    container_name: com-kuituoshi-demo
    image: com.kuituoshi/demo:0.0.1
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - dev
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=5005,suspend=y,server=y
      SPRINGBOOT_JAR_NAME: demo-0.0.1.jar

networks:
 dev:
   external: true
