apiVersion: v1
kind: Pod
metadata:
  labels:
    app: java-jdk-8.144
spec:
  containers:
    - command:
        - sleep
        - "99d"
      image: 'changel/java:jdk8.144.jce'
      name: maven
      volumeMounts:
        - mountPath: /var/lib/maven/repository
          name: maven-cache
    - name: kaniko
      image: changel/kaniko-executor:debug
      command:
        - sleep
        - "99d"
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: docker-config
    - name: tools
      image: registry-intl-vpc.cn-hongkong.aliyuncs.com/batie/jenkins:tools
      command:
        - sleep
        - "99d"
  restartPolicy: Never
  serviceAccountName: jenkins-admin
  terminationGracePeriodSeconds: 30
  volumes:
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-storage
    - name: docker-config
      secret:
        secretName: aliyun-vpc-image
        items:
        - key: .dockerconfigjson
          path: config.json